name: CI/CD Pipeline (demo-app2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}/demo-app2

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    needs: sonar-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.python-version }}-${{ github.sha }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker stop demo-app2 || true
          docker rm demo-app2 || true
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:3.10-${{ github.sha }}
          docker run -d --name demo-app2 -p 5000:5000 ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:3.10-${{ github.sha }}
